name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server
        run: |
          chmod +x ./.scripts/deploy.sh
          "cd /app && ./.scripts/deploy.sh"
        shell: bash
       
