name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: checkout code
        run: |
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo timedatectl set-timezone Asia/Kolkata
          sudo apt-get install php -y
          #sudo apt-get install curl git zip unzip -y
          sudo git clone https://github.com/Maheshbhoyar2302/laravel-docker2.git  /home/ubuntu/app
          sudo chmod -R 777 /home/ubuntu/app/
          sudo chown -R www-data:www-data /home/ubuntu/app/storage/
          sudo chmod -R ugo+rw /home/ubuntu/app/storage
          sudo chown -R www-data:www-data /home/ubuntu/app/bootstrap/cache/
          sudo chmod -R ugo+rw /home/ubuntu/app/bootstrap/cache/
          sudo curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          cd /home/ubuntu/app/  && composer install
          
          sudo php artisan serve --host=0.0.0.0 --port=8000
       
